spring.application.name=JobPortalBackend
# DataSource Configuration
spring.datasource.url=jdbc:mysql://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/jobportaldatabase
spring.datasource.username=xxxxxxx
spring.datasource.password=xxxxxxx
#spring.datasource.url=jdbc:mysql://localhost:3306/jobportaldatabase
#spring.datasource.username=root
#spring.datasource.password=niwas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
# validate/ none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Key
security.jwt.secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# AWS S3 Configuration
aws.s3.bucket-name=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# AWS Credentials (if not using default provider chain)
aws.access-key-id=xxxxxxxxxxxxxxxxxx
aws.secret-access-key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
aws.region=xxxxxxxxxxx

# Server Configuration
spring.servlet.multipart.max-file-size=05MB
spring.servlet.multipart.max-request-size=10MB

